### ISSUE TITLE
Help command: add new commands and send it in text instead of on a picture.

### ISSUE THREAD

**Issue by technonerdz** [FRC-Bot/FRCBot-ChatBot#1]
Right now, the help section is too big to be sent in one message by the bot. The bot is sending an image with the commands.

It would be great if we could send the commands in text to the user. We could send a bunch of messages at the same time with a different command on each line.

**Comment by jaredhasenklein** [comment]
What is the reason that it is too big to send? Can Messenger not handle it or what's happening?

**Comment by technonerdz** [comment]
The Messenger API is limiting the number of characters. In a normal conversation, Messenger does not have a character limit but there is one for Bots. If you send something with too many characters, it would not be send.

**Comment by technonerdz** [comment]
That's why the Sponsor command only works with certain teams. Teams with too many sponsors do not work.

**Comment by jaredhasenklein** [comment]
Ah I see...looks like 320 characters, right? Can you paste in the plain text of the help image here so that I don't need to rewrite to play with it?

**Comment by technonerdz** [comment]
Hello! I am the Facebook ChatBot for FRC Bot! You can ask me the following questions:
'NextMatch TEAMNUMBER' to see the next match for a team.
'Status TEAMNUMBER' to see the stats of a team in their current event.
'Website TEAMNUMBER' to get the website of a team.
'Location TEAMNUMBER' to get the location of a team.
'Nickname TEAMNUMBER' to get the name of a team.

**Comment by jaredhasenklein** [comment]
What about just shortening the text to something like this?:

`Hello! I am the Facebook FRC ChatBot! You can ask me the following questions (# for team number):`
`'NextMatch #' to see a team's next match`
`'Status #' to see a team's current event stats`
`'Website #' to get a team's URL`
`'Location #' to get a team's location`
`'Nickname #' to get a team's name`

**Comment by technonerdz** [comment]
It won't work in the future when we add more commands

**Comment by technonerdz** [comment]
But you are right! This is cleaner!

**Comment by technonerdz** [comment]
https://github.com/FRC-Bot/FRCBot-images/pull/2 made this much cleaner. Most commands were added.
