### ISSUE TITLE
Alliance subscribed team is on

### ISSUE THREAD

**Issue by ArchdukeTim** [FRC-Bot/FRCBot-ChatBot#15]
There should be a way to report which alliance the subscribed team is on. I hate having to go to TBA anyway to figure out if I won or lost. Defeats the purpose of it

**Comment by technonerdz** [comment]
I'll try to fix this tonight or tomorrow

**Comment by technonerdz** [comment]
I fixed it.

This is how it looks:
![yo4wrr](https://cloud.githubusercontent.com/assets/1951283/24824706/994dafe0-1bde-11e7-90e6-b4012cc85a2d.png)

**Comment by ArchdukeTim** [comment]
Thank you so much! Not too excited to see frc1418 lost the game though 😂
