### ISSUE TITLE
Get robot picture by year

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Bot/FRCBot-ChatBot#5]
User input:
**Picture <<year>> <<team>>**
_Example: Picture 2016 1836_ 

Output:
**Photos of robot (or at the very least URLs)**

Utilize:
**http://www.thebluealliance.com/api/v2/team/_TEAM_/_YEAR_/media?X-TBA-App-Id=frcbot:messengerchatbot:1**
_Example: http://www.thebluealliance.com/api/v2/team/frc1836/2016/media?X-TBA-App-Id=frcbot:messengerchatbot:1_

**Comment by technonerdz** [comment]
done!

**Comment by jaredhasenklein** [comment]
Looks good! Is there a way to get more images or just the primary on TBA?
