### ISSUE TITLE
Picture error

### ISSUE THREAD

**Issue by jaredhasenklein** [FRC-Bot/FRCBot-ChatBot#6]
I am not getting a photo response for some random teams who do have photos available on TBA. Reproduce by asking:
`picture 2016 973`

**UPDATE: I figured out why but still no solution**
If you got to 973's TBA page, you will notice that they have two images. The first image is blank while the second image is actual content. The bot only pulls the first photo. Therefore, it cannot return the non-blank one. Is it possible to tell the bot to send all pictures?

**Comment by technonerdz** [comment]
I see that! Maybe @fangeugene could fix this on TBA http://www.thebluealliance.com/team/973

**Comment by jaredhasenklein** [comment]
I don't think that this is the solution. Eugene could manually fix this one but what happens if this ever happens again?

**Comment by technonerdz** [comment]
Yes I know that I will have to change it on my side. I am working on other things right now. If someone wants to take a look, it would be cool.

**Comment by jaredhasenklein** [comment]
Beyond my capabilities

**Comment by technonerdz** [comment]
Sending more than 1 images is beyond mine too. I think I should focus on some other things. This is not a priority.

**Comment by jaredhasenklein** [comment]
Agreed

**Comment by technonerdz** [comment]
I decided I don't care!

**Comment by fangeugene** [comment]
We're working on a flow to make it easier to crowdsource when images are bad. https://github.com/the-blue-alliance/the-blue-alliance/issues/1642

**Comment by technonerdz** [comment]
This guy have a good point: ![img_1706](https://cloud.githubusercontent.com/assets/1951283/19894891/169c879a-a025-11e6-8c5f-8bb3cfdd5047.PNG)
